name: Linting

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "lintint"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          pip install pre-commit

      - name: Check pre-commit lint checks
        run: pre-commit
