name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "ReleaseBuild"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.9"]

    permissions:
      # required for all workflows
      security-events: read
      actions: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Setup"
        run: |
          pip3 install --upgrade twine hatch
        working-directory: "."

      - name: "Build"
        run: |
          make build
        working-directory: "."

      - name: "Publish"
        id: publish
        run: |
          python3 -m twine upload -u __token__ -p "${{ secrets.PYPI_SECRET }}" dist/*
        working-directory: "."

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="$tag" \
              --notes-from-tag

      - name: Upload Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release upload "$tag" ./vanillacorn.py
        working-directory: "."
